version: '3.4'

services:
  dev-enterprisebot-api:

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - SecretsPath=/run/secrets

      - Serilog__WriteTo__1__Args__serverUrl=http://dev-seq-api:5341
    ports:
      - "80"
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 3s
        window: 15s
      update_config:
        order: start-first
      labels:
        - traefik.enable=true

        - traefik.http.routers.dev-entbot-api-router-http.rule=Host(`api.api.entbotdev.tk`)
        - traefik.http.routers.dev-entbot-api-router-http.entrypoints=http
        - traefik.http.routers.dev-entbot-api-router-http.middlewares=https-redirect

        - traefik.http.routers.dev-entbot-api-router-https.rule=Host(`api.api.entbotdev.tk`)
        - traefik.http.routers.dev-entbot-api-router-https.entrypoints=https
        - traefik.http.routers.dev-entbot-api-router-https.tls=true
        - traefik.http.routers.dev-entbot-api-router-https.tls.certresolver=le

        - traefik.http.services.dev-entbot-api-service-https.loadbalancer.server.port=80
        - traefik.http.services.dev-entbot-api-service-https.loadbalancer.server.scheme=http

        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
    secrets:
      - Development_Api_ConnectionStrings__Game
      - Development_Api_ConnectionStrings__Hangfire
    networks:
      - traefik-public
      - dev-entbot-network


  dev-enterprisebot-background:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - SecretsPath=/run/secrets

      - Serilog__WriteTo__1__Args__serverUrl=http://dev-seq-background:5341
    ports:
      - "80"
    deploy:
      restart_policy:
        condition: any
        delay: 3s
        window: 15s
      update_config:
        order: start-first
      labels:
        - traefik.enable=true

        - traefik.http.routers.dev-entbot-background-router-http.rule=Host(`background.api.entbotdev.tk`)
        - traefik.http.routers.dev-entbot-background-router-http.entrypoints=http
        - traefik.http.routers.dev-entbot-background-router-http.middlewares=https-redirect

        - traefik.http.routers.dev-entbot-background-router-https.rule=Host(`background.api.entbotdev.tk`)
        - traefik.http.routers.dev-entbot-background-router-https.entrypoints=https
        - traefik.http.routers.dev-entbot-background-router-https.tls=true
        - traefik.http.routers.dev-entbot-background-router-https.tls.certresolver=le

        - traefik.http.services.dev-entbot-background-service-https.loadbalancer.server.port=80
        - traefik.http.services.dev-entbot-background-service-https.loadbalancer.server.scheme=http

        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
    secrets:
      - Development_Background_ConnectionStrings__HangfireDb
    networks:
      - traefik-public
      - dev-entbot-network


  dev-enterprisebot-vk:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - SecretsPath=/run/secrets

      - Serilog__WriteTo__1__Args__serverUrl=http://dev-seq-vk:5341

      - ApiSettings__ApiServerUrl=http://dev-enterprisebot-api:80
    ports:
      - "80"
    deploy:
      restart_policy:
        condition: any
        delay: 3s
        window: 15s
      update_config:
        order: start-first      
      labels:
        - traefik.enable=true

        - traefik.http.routers.dev-entbot-vk-router-http.rule=Host(`vk.api.entbotdev.tk`)
        - traefik.http.routers.dev-entbot-vk-router-http.entrypoints=http
        - traefik.http.routers.dev-entbot-vk-router-http.middlewares=https-redirect

        - traefik.http.routers.dev-entbot-vk-router-https.rule=Host(`vk.api.entbotdev.tk`)
        - traefik.http.routers.dev-entbot-vk-router-https.entrypoints=https
        - traefik.http.routers.dev-entbot-vk-router-https.tls=true
        - traefik.http.routers.dev-entbot-vk-router-https.tls.certresolver=le

        - traefik.http.services.dev-entbot-vk-service-https.loadbalancer.server.port=80
        - traefik.http.services.dev-entbot-vk-service-https.loadbalancer.server.scheme=http

        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
    secrets:
      - Development_VK_ConnectionStrings__ErrorsPostgres
      - Development_VK_ConnectionStrings__Redis
      - Development_VK_VkSettings__GroupId
      - Development_VK_VkSettings__AccessToken
      - Development_VK_VkSettings__SecretKey
      - Development_VK_VkSettings__Confirmation
    networks:
      - traefik-public
      - dev-entbot-network


  dev-seq-api:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "80"
      - "5341"
    deploy:
      restart_policy:
        condition: any
        delay: 3s
        window: 15s
      update_config:
        order: stop-first
      labels:
        - traefik.enable=true

        - traefik.http.routers.dev-seq-api-router-http.rule=Host(`api.seq.api.entbotdev.tk`)
        - traefik.http.routers.dev-seq-api-router-http.entrypoints=http
        - traefik.http.routers.dev-seq-api-router-http.middlewares=https-redirect

        - traefik.http.routers.dev-seq-api-router-https.rule=Host(`api.seq.api.entbotdev.tk`)
        - traefik.http.routers.dev-seq-api-router-https.entrypoints=https
        - traefik.http.routers.dev-seq-api-router-https.tls=true
        - traefik.http.routers.dev-seq-api-router-https.tls.certresolver=le

        - traefik.http.services.dev-seq-api-service-https.loadbalancer.server.port=80

        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
    volumes:
      - dev-seq-api-data:/data
    networks:
      - traefik-public
      - dev-entbot-network

  dev-seq-background:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "80"
      - "5341"
    deploy:
      restart_policy:
        condition: any
        delay: 3s
        window: 15s
      update_config:
        order: stop-first
      labels:
        - traefik.enable=true

        - traefik.http.routers.dev-seq-background-router-http.rule=Host(`background.seq.api.entbotdev.tk`)
        - traefik.http.routers.dev-seq-background-router-http.entrypoints=http
        - traefik.http.routers.dev-seq-background-router-http.middlewares=https-redirect

        - traefik.http.routers.dev-seq-background-router-https.rule=Host(`background.seq.api.entbotdev.tk`)
        - traefik.http.routers.dev-seq-background-router-https.entrypoints=https
        - traefik.http.routers.dev-seq-background-router-https.tls=true
        - traefik.http.routers.dev-seq-background-router-https.tls.certresolver=le
        
        - traefik.http.services.dev-seq-background-service-https.loadbalancer.server.port=80

        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
    volumes:
      - dev-seq-background-data:/data
    networks:
      - traefik-public
      - dev-entbot-network

  dev-seq-vk:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "80"
      - "5341"
    deploy:
      restart_policy:
        condition: any
        delay: 3s
        window: 15s
      update_config:
        order: stop-first
      labels:
        - traefik.enable=true

        - traefik.http.routers.dev-seq-vk-router-http.rule=Host(`vk.seq.api.entbotdev.tk`)
        - traefik.http.routers.dev-seq-vk-router-http.entrypoints=http
        - traefik.http.routers.dev-seq-vk-router-http.middlewares=https-redirect

        - traefik.http.routers.dev-seq-vk-router-https.rule=Host(`vk.seq.api.entbotdev.tk`)
        - traefik.http.routers.dev-seq-vk-router-https.entrypoints=https
        - traefik.http.routers.dev-seq-vk-router-https.tls=true
        - traefik.http.routers.dev-seq-vk-router-https.tls.certresolver=le

        - traefik.http.services.dev-seq-vk-service-https.loadbalancer.server.port=80

        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
    volumes:
      - dev-seq-vk-data:/data
    networks:
      - traefik-public
      - dev-entbot-network

  dev-db-redis:
    command: >
      /run/secrets/redis.conf
    ports:
      - "6379"
    deploy:
      restart_policy:
        condition: any
        delay: 3s
        window: 15s
      update_config:
        order: start-first
    secrets:
      - redis.conf
    networks:
      - dev-entbot-network

volumes:
  dev-seq-api-data:
  dev-seq-background-data:
  dev-seq-vk-data:

secrets:
  Development_Api_ConnectionStrings__Game:
    external: true
  Development_Api_ConnectionStrings__Hangfire:
    external: true

  Development_Background_ConnectionStrings__HangfireDb:
    external: true

  Development_VK_ConnectionStrings__ErrorsPostgres:
    external: true
  Development_VK_ConnectionStrings__Redis:
    external: true
  Development_VK_VkSettings__GroupId:
    external: true
  Development_VK_VkSettings__AccessToken:
    external: true
  Development_VK_VkSettings__SecretKey:
    external: true
  Development_VK_VkSettings__Confirmation:
    external: true

  redis.conf:
    external: true
    
networks:
  traefik-public:
    external: true
  dev-entbot-network: