version: '3.4'

services:
  prod.enterprisebot.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80

      - SecretsPath=/run/secrets

      - Serilog__WriteTo__1__Args__serverUrl=http://prod.seq.api:5341
    ports:
      - "5100:80"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        window: 15s
    tmpfs:
      - /run/secrets
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    secrets:
      - Production_Api_ConnectionStrings__Game
      - Production_Api_ConnectionStrings__Hangfire


  prod.enterprisebot.background:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80

      - Serilog__WriteTo__1__Args__serverUrl=http://prod.seq.background:5341
    ports:
      - "5101:80"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        window: 15s
    tmpfs:
      - /run/secrets
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    secrets:
      - Production_Background_ConnectionStrings__HangfireDb


  prod.enterprisebot.vk:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80

      - Serilog__WriteTo__1__Args__serverUrl=http://prod.seq.vk:5341

      - ApiSettings__ApiServerUrl=http://prod.enterprisebot.api:80
    ports:
      - "5102:80"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        window: 15s
    tmpfs:
      - /run/secrets
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    secrets:
      - Production_VK_ConnectionStrings__ErrorsPostgres
      - Production_VK_ConnectionStrings__Redis
      - Production_VK_VkSettings__GroupId
      - Production_VK_VkSettings__AccessToken
      - Production_VK_VkSettings__SecretKey
      - Production_VK_VkSettings__Confirmation


  prod.seq.api:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5350:80"
      - "5351:5341"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        window: 15s
    volumes:
      - prod-seq-api-data:/data

  prod.seq.background:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5360:80"
      - "5361:5341"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        window: 15s
    volumes:
      - prod-seq-background-data:/data

  prod.seq.vk:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5370:80"
      - "5371:5341"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        window: 15s
    volumes:
      - prod-seq-vk-data:/data


  prod.db.redis:
    command: >
      /run/secrets/redis.conf
    ports:
      - "6379"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        window: 15s
    tmpfs:
      - /run/secrets
    secrets:
      - redis.conf


volumes:
  prod-seq-api-data:
  prod-seq-background-data:
  prod-seq-vk-data:


secrets:
  Production_Api_ConnectionStrings__Game:
    external: true
  Production_Api_ConnectionStrings__Hangfire:
    external: true

  Production_Background_ConnectionStrings__HangfireDb:
    external: true

  Production_VK_ConnectionStrings__ErrorsPostgres:
    external: true
  Production_VK_ConnectionStrings__Redis:
    external: true
  Production_VK_VkSettings__GroupId:
    external: true
  Production_VK_VkSettings__AccessToken:
    external: true
  Production_VK_VkSettings__SecretKey:
    external: true
  Production_VK_VkSettings__Confirmation:
    external: true

  redis.conf:
    external: true
  